version: '3'

services:
  mongodb:
    image: 'mongo:4.4-bionic'
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "27017:27017"
    volumes:
      - 'mongodb_data:/bitnami/mongodb'
    networks:
      - apps-network

  movie-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:4200"
    environment:
      JWT_SECRET: ${JWT_SECRET}
    networks:
      - apps-network
    depends_on:
      - mongodb

networks:
  apps-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local